### ISSUE TITLE
Process thermal video?

### ISSUE THREAD

**Issue by ykn96** [SanNianYiSi/thermal_parser#2]
Hi. Thanks for the great repo. I can see it convert thremal photos.

Can it convert thermal videos? Eg i have a thermal video in whitehot, and i want to convert it to ironred.

**Comment by SanNianYiSi** [comment]
sorry, the R-JPEG image format used to store infrared images does not support common video encoding formats like H.264, H.265, etc. 
so if you have a video file captured by an infrared camera, it's likely that this video file only contains videos rendered with pseudo-colors and has lost the infrared temperature data.
of course, there are some video formats that can store infrared data, but they are relatively rare and customized, and I am not very familiar with them.
